from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = ROOT / "data" / "sine_wave_binary_classification"
OUTPUT_ROOT = ROOT / "outputs" / "sine_wave_binary_classification"
AUDIO_OUTPUT_DIR = OUTPUT_ROOT / "sine_wave"
CLASSIFIER_OUTPUT_DIR = OUTPUT_ROOT / "binary_classification"
VISUAL_AUDIO_DIR = OUTPUT_ROOT / "visuals" / "audio"
VISUAL_CLASSIFIER_DIR = OUTPUT_ROOT / "visuals" / "classifier"
EVALUATION_OUTPUT_DIR = OUTPUT_ROOT / "evaluation"
EVALUATION_DIR = ROOT / "evaluation"

SPECTROGRAM_DATA_ROOT = ROOT / "data" / "spectrogram_classification"
SPECTROGRAM_OUTPUT_ROOT = ROOT / "outputs" / "spectrogram_classification"
SPECTROGRAM_WEIGHT_DIR = SPECTROGRAM_OUTPUT_ROOT / "weights"
SPECTROGRAM_MODEL_DIR = SPECTROGRAM_OUTPUT_ROOT / "models"
SPECTROGRAM_METRICS_DIR = SPECTROGRAM_OUTPUT_ROOT / "metrics"
SPECTROGRAM_FEATURE_DIR = SPECTROGRAM_OUTPUT_ROOT / "features"
SPECTROGRAM_PREDICTION_DIR = SPECTROGRAM_OUTPUT_ROOT / "predictions"
SPECTROGRAM_EVALUATION_DIR = SPECTROGRAM_OUTPUT_ROOT / "evaluation"
VISUAL_SPECTROGRAM_DIR = SPECTROGRAM_OUTPUT_ROOT / "visuals"
VISUAL_SPECTROGRAM_FEATURE_DIR = VISUAL_SPECTROGRAM_DIR / "features"
VISUAL_SPECTROGRAM_MODEL_DIR = VISUAL_SPECTROGRAM_DIR / "models"
VISUAL_SPECTROGRAM_README_DIR = SPECTROGRAM_OUTPUT_ROOT / "readme"
