from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOG_ROOT = ROOT / "logs"
DATA_ROOT = ROOT / "data" / "sine_wave_binary_classification"
OUTPUT_ROOT = ROOT / "outputs" / "sine_wave_binary_classification"
AUDIO_OUTPUT_DIR = OUTPUT_ROOT / "sine_wave"
CLASSIFIER_OUTPUT_DIR = OUTPUT_ROOT / "binary_classification"
VISUAL_AUDIO_DIR = OUTPUT_ROOT / "visuals" / "audio"
VISUAL_CLASSIFIER_DIR = OUTPUT_ROOT / "visuals" / "classifier"
EVALUATION_OUTPUT_DIR = OUTPUT_ROOT / "evaluation"
EVALUATION_DIR = ROOT / "evaluation"

SPECTROGRAM_DATA_ROOT = ROOT / "data" / "spectrogram_classification"
SPECTROGRAM_OUTPUT_ROOT = ROOT / "outputs" / "spectrogram_classification"
SPECTROGRAM_WEIGHT_DIR = SPECTROGRAM_OUTPUT_ROOT / "weights"
SPECTROGRAM_MODEL_DIR = SPECTROGRAM_OUTPUT_ROOT / "models"
SPECTROGRAM_METRICS_DIR = SPECTROGRAM_OUTPUT_ROOT / "metrics"
SPECTROGRAM_FEATURE_DIR = SPECTROGRAM_OUTPUT_ROOT / "features"
SPECTROGRAM_PREDICTION_DIR = SPECTROGRAM_OUTPUT_ROOT / "predictions"
SPECTROGRAM_EVALUATION_DIR = SPECTROGRAM_OUTPUT_ROOT / "evaluation"
VISUAL_SPECTROGRAM_DIR = SPECTROGRAM_OUTPUT_ROOT / "visuals"
VISUAL_SPECTROGRAM_FEATURE_DIR = VISUAL_SPECTROGRAM_DIR / "features"
VISUAL_SPECTROGRAM_MODEL_DIR = VISUAL_SPECTROGRAM_DIR / "models"
VISUAL_SPECTROGRAM_README_DIR = SPECTROGRAM_OUTPUT_ROOT / "readme"

SYMBOLIC_DATA_ROOT = ROOT / "data" / "symbolic_music_generation"
SYMBOLIC_OUTPUT_ROOT = ROOT / "outputs" / "symbolic_music_generation"
SYMBOLIC_METRICS_DIR = SYMBOLIC_OUTPUT_ROOT / "metrics"
SYMBOLIC_GENERATED_DIR = SYMBOLIC_OUTPUT_ROOT / "generated"
SYMBOLIC_TABLE_DIR = SYMBOLIC_OUTPUT_ROOT / "tables"
SYMBOLIC_EVALUATION_DIR = SYMBOLIC_OUTPUT_ROOT / "evaluation"
VISUAL_SYMBOLIC_DIR = SYMBOLIC_OUTPUT_ROOT / "visuals"
VISUAL_SYMBOLIC_README_DIR = SYMBOLIC_OUTPUT_ROOT / "readme"

AUTOMATIC_INSTRUMENTATION_DATA_ROOT = ROOT / "data" / "automatic_music_instrumentation"
AUTOMATIC_INSTRUMENTATION_NOTEBOOK_DIR = AUTOMATIC_INSTRUMENTATION_DATA_ROOT / "notebooks"
AUTOMATIC_INSTRUMENTATION_PROCESSED_DIR = AUTOMATIC_INSTRUMENTATION_DATA_ROOT / "processed"
AUTOMATIC_INSTRUMENTATION_PROCESSED_ZIP_DIR = AUTOMATIC_INSTRUMENTATION_DATA_ROOT / "processed_zips"
AUTOMATIC_INSTRUMENTATION_RAW_DIR = AUTOMATIC_INSTRUMENTATION_DATA_ROOT / "raw"
AUTOMATIC_INSTRUMENTATION_CLEAN_MIDI_DIR = AUTOMATIC_INSTRUMENTATION_DATA_ROOT / "lmd_clean_midi"
AUTOMATIC_INSTRUMENTATION_OUTPUT_ROOT = ROOT / "outputs" / "automatic_music_instrumentation"
AUTOMATIC_INSTRUMENTATION_LOG_ROOT = LOG_ROOT / "automatic_music_instrumentation"
AUTOMATIC_INSTRUMENTATION_MODEL_DIR = AUTOMATIC_INSTRUMENTATION_OUTPUT_ROOT / "models"
AUTOMATIC_INSTRUMENTATION_METRICS_DIR = AUTOMATIC_INSTRUMENTATION_OUTPUT_ROOT / "metrics"
AUTOMATIC_INSTRUMENTATION_VISUAL_DIR = AUTOMATIC_INSTRUMENTATION_OUTPUT_ROOT / "visuals"
